### ISSUE TITLE
Convert to HTML fail when header is only CJK characters

### ISSUE THREAD

**Issue by milligramme** [MikeMcQuaid/GitHub-Markdown.tmbundle#16]
runing 2.0-beta.12.26

Header item will convert to H1-6 with id.
If the contents is only CJK chars, last quotation mark for id is short.

here is a sample.

``` md
# 第一階層

top level

## 第二階層

second level

## 第三階層

third level
```

`Show Preview` shots

![screen shot 2016-10-26 10 19 05](https://cloud.githubusercontent.com/assets/294127/19710007/f2d95dec-9b65-11e6-942e-7714f3e603d9.png)

output from `Convert Document to HTML`

``` html
<h1 id=">第一階層</h1>

<p>top level</p>

<h2 id=">第二階層</h2>

<p>second level</p>

<h2 id=">第三階層</h2>

<p>third level</p>
```

I expect this output.

``` html
<h1 id="">第一階層</h1>

<p>top level</p>

<h2 id="">第二階層</h2>

<p>second level</p>

<h2 id="">第三階層</h2>

<p>third level</p>
```

**Comment by milligramme** [comment]
this probrem seems to be caused by redcarpet.rb vmg/redcarpet#538

**Comment by MikeMcQuaid** [comment]
Going to close this in favour of the upstream issue.

**Comment by milligramme** [comment]
installing redcarpet v3.4.0 fixed this issue.

```
$ sudo /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/gem install redcarpet
```
