### ISSUE TITLE
Words containing two underscores break highlighting of rest of document

### ISSUE THREAD

**Issue by noniq** [MikeMcQuaid/GitHub-Markdown.tmbundle#20]
Screenshot:

![bildschirmfoto 2017-04-27 um 14 46 06](https://cloud.githubusercontent.com/assets/244158/25484003/6e439ea2-2b58-11e7-9cc5-5fbf267c5ed2.png)

Note that the following headline is not highlighted at all. It seem that this is caused by the `markup.italic.markdown` scope extending behind the second underscore.

Here’s how the same document looks like when I disable the GitHub-Markdown bundle:

![bildschirmfoto 2017-04-27 um 14 49 27](https://cloud.githubusercontent.com/assets/244158/25484076/bc1c90d4-2b58-11e7-9508-ba3e8a4d6c3f.png)

I found https://github.com/MikeMcQuaid/GitHub-Markdown.tmbundle/blob/master/Syntaxes/Markdown%20(GitHub%20Italics).tmLanguage which seems to be the culprit, but I couldn’t figure out its purpose in the first place, so I’m not sure how to fix this.

**Comment by MikeMcQuaid** [comment]
I can't find an official description but the original intent was to provide this additional feature that GitHub Flavoured Markdown provides:

> ### Escape Underscores in Words
> It is not reasonable to italicize just part of a word, therefore words containing multiple underscores have their inner underscores escaped. This foo_bar_baz does not turn into foobarbaz.
>
> https://www.drupal.org/project/gfm

**Comment by noniq** [comment]
Makes sense. But it seems that TextMate's own Markdown grammar already handles this (see second screenshot)?

**Comment by MikeMcQuaid** [comment]
@noniq Yes, you are correct. 👍 to tearing out the new buggy, italic stuff from me.

**Comment by noniq** [comment]
Hm okay, not sure what exactly I did wrong, but TextMate’s own Markdown grammar does indeed italicize part of words. So it is still necessary to somehow override this feature in this bundle.

I’m right now experimenting a bit, the following seems to work fine:
<img width="695" alt="bildschirmfoto 2017-04-28 um 17 53 30" src="https://cloud.githubusercontent.com/assets/244158/25536565/9edd764e-2c3b-11e7-937e-36fac5fcf5b4.png">

I simplified the look-behind pattern to make sure the rule also matches the first underscore in a word. I also changed the injection selector to `(L:text.html.markdown)` (removing the `markup.italic.markdown` part). Finally, I changed name to `markup.other` to prevent the matched underscores from getting italicized (which does not make a different in any font I know of, but who knows …)

I’ve checked with a few Markdown documents, and they all seem to be highlighted correctly. But I’m totally sure that there could be some edge cases where something breaks. Any ideas what else to check or improve?

**Comment by MikeMcQuaid** [comment]
> I’ve checked with a few Markdown documents, and they all seem to be highlighted correctly. But I’m totally sure that there could be some edge cases where something breaks. Any ideas what else to check or improve?

Seems great to me; definitely better than what's there currently!

**Comment by noniq** [comment]
I merged this for now. I’ll keep an eye on it and refine if necessary.
