### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by MtnBiker** [MikeMcQuaid/GitHub-Markdown.tmbundle#26]
When I invoke Bundles>MarkDown (GitHub) Preview, I get (copied from the window)

    Markdown (GitHub) Preview
    README.md
    Theme:  
    Please install the Redcarpet and Pygments.rb RubyGems by running the following:

    /usr/bin/gem install --user redcarpet pygments.rb
    Ignoring bcrypt-3.1.7 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.7 Ignoring binding_of_caller-0.7.3.pre1 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.3.pre1 Ignoring binding_of_caller-0.7.2 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.2 Ignoring byebug-8.1.0 because its extensions are not built. Try: gem pristine byebug --version 8.1.0 Ignoring byebug-8.0.1 because its extensions are not built. Try: gem pristine byebug --version 8.0.1 Ignoring byebug-6.0.2 because its extensions are not built. Try: gem pristine byebug --version 6.0.2 Ignoring byebug-3.4.0 because its extensions are not built. Try: gem pristine byebug --version 3.4.0 Ignoring debug_inspector-0.0.2 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.2 Ignoring gdal-1.0.0 because its extensions are not built. Try: gem pristine gdal --version 1.0.0 Ignoring nokogiri-1.6.7.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.2 Ignoring nokogiri-1.6.7.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.7.1 Ignoring nokogiri-1.6.6.2 because its extensions are not built. Try: gem pristine nokogiri --version 1.6.6.2 Ignoring pg-0.18.4 because its extensions are not built. Try: gem pristine pg --version 0.18.4 Ignoring posix-spawn-0.3.11 because its extensions are not built. Try: gem pristine posix-spawn --version 0.3.11 Ignoring puma-2.15.3 because its extensions are not built. Try: gem pristine puma --version 2.15.3 Ignoring redcarpet-3.3.4 because its extensions are not built. Try: gem pristine redcarpet --version 3.3.4 Ignoring sqlite3-1.3.10 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.10 Ignoring sqlite3-1.3.9 because its extensions are not built. Try: gem pristine sqlite3 --version 1.3.9 Ignoring unf_ext-0.0.7.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.1 Ignoring websocket-driver-0.6.3 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.3 Ignoring yajl-ruby-1.2.1 because its extensions are not built. Try: gem pristine yajl-ruby --version 1.2.1$

So I tried
    $ /usr/bin/gem install --user redcarpet pygments.rb
    dyld: lazy symbol binding failed: Symbol not found: _rb_ary_new_from_values
      Referenced from: /Users/gscar/.gem/ruby/2.4.0/gems/psych-2.2.4/lib/psych.bundle
      Expected in: flat namespace

    dyld: Symbol not found: _rb_ary_new_from_values
      Referenced from: /Users/gscar/.gem/ruby/2.4.0/gems/psych-2.2.4/lib/psych.bundle
      Expected in: flat namespace

    Abort trap: 6
    $ gem install --user redcarpet pygments.rb
    Building native extensions.  This could take a while...
    Successfully installed redcarpet-3.4.0
    Successfully installed pygments.rb-1.1.2
    2 gems installed

Relaunched TextMate 2.0-rc.4 and have same problem. Also Cntl-Opt-Cmd-P doesn't work, but maybe that's my issue.

Thank you for the bundle. I might not bother to comment, but my main use of Markdown is for GitHub and when I go to select Markdown, I naturally select the (GitHub) version and get the error, then I have to redo with just Markdown. And I can't make the GitHub version leave my menu, even though it's not selected in the  Preferences>Bundles.

**Comment by MikeMcQuaid** [comment]
> $ /usr/bin/gem install --user redcarpet pygments.rb
> dyld: lazy symbol binding failed: Symbol not found: _rb_ary_new_from_values
> Referenced from: /Users/gscar/.gem/ruby/2.4.0/gems/psych-2.2.4/lib/psych.bundle
> Expected in: flat namespace

This is an issue with your personal Ruby not the bundle and I'm able to provide that level of support, sorry. Thanks for the kind words, though!

**Comment by MtnBiker** [comment]
Thanks for the prompt response.

Greg
