### ISSUE TITLE
math inside

### ISSUE THREAD

**Issue by chipbrock** [MikeMcQuaid/GitHub-Markdown.tmbundle#27]
hi
I believe I've installed your Git version of markdown (thanks!).

I went "there" because I am stunned to discover that plain-ole markdown in TextMate seems to ignore mathematics, sort of. In particular if I type $A_b$ and then some blah...

it treats the latex subscript mark as em and so I get 

 $A<em>b and then some blah...</em>  

it of course renders like italic and escapes the second $. 

I use mathjax. 

So I hoped that your tool would fix that, since my understanding is that math is resident in the git version of markdown (kramdown?). But the same thing happens. 

Any suggestions? 

...sorry. Edited to note that I'm using TextMate 2.0-rc.4

thanks
Ray Brock

**Comment by MikeMcQuaid** [comment]
Sorry, I have no idea about mathjax.
