### ISSUE TITLE
Preview has trouble with fenced code

### ISSUE THREAD

**Issue by nathany** [MikeMcQuaid/GitHub-Markdown.tmbundle#3]
This doesn't look right.

<img width="1060" alt="preview" src="https://cloud.githubusercontent.com/assets/4566/12874501/4f544494-cd92-11e5-87d1-ce53c1b40c90.png">

**Comment by MikeMcQuaid** [comment]
That seems to be using the wrong Markdown preview (i.e. not the GitHub one which would show `Markdown (GitHub) Preview`). How are you activating it?

**Comment by nathany** [comment]
Yah, you're right. I was going to Markdown / Preview in the status bar menu, but should've been going to Markdown (GitHub) / Preview.

Guess this is a non-issue, other than that it was easy to confuse. It seems the keyboard shortcut picks the right one.

One odd thing is that the language picker in the status bar only shows "Markdown", though the gear shows both "Markdown" and "Markdown (GitHub)".

**Comment by MikeMcQuaid** [comment]
> Yah, you're right. I was going to Markdown / Preview in the status bar menu, but should've been going to Markdown (GitHub) / Preview.

Yup :+1: 

> Guess this is a non-issue, other than that it was easy to confuse. It seems the keyboard shortcut picks the right one.

Yeh, it does.

> One odd thing is that the language picker in the status bar only shows "Markdown", though the gear shows both "Markdown" and "Markdown (GitHub)".

Yeh, I can see that being a little confusing but that's because this is an extension of the Markdown bundle rather than a completely new implementation.
