### ISSUE TITLE
Some of the C syntax isn't picked up within code fences

### ISSUE THREAD

**Issue by hovsater** [MikeMcQuaid/GitHub-Markdown.tmbundle#33]
Here's a screenshot of the following C code:

<img width="294" alt="Screenshot 2020-09-04 at 14 50 05" src="https://user-images.githubusercontent.com/503025/92241079-ec5d7980-eebd-11ea-8e45-76aa35374c9b.png">

Here's the same code within code fences in a Markdown file:

<img width="325" alt="Screenshot 2020-09-04 at 14 50 39" src="https://user-images.githubusercontent.com/503025/92241123-013a0d00-eebe-11ea-80af-cbb4af0c0f4f.png">

As you can see the following things are different:

- `void` isn't highlighted
- Strings within the function body aren't highlighted
- `return 0` isn't highlighted either (although I forgot to include that in the screenshot)

**Comment by noniq** [comment]
Unfortunately I don't have time to investigate this myself, but if someone comes up with a fix I'd be more than happy to merge it.

**Comment by hovsater** [comment]
Turns out this is a limitation of how the C bundle implemented its syntax. Closing this.
